# Generated by Django 4.0.2 on 2022-03-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_city_order_country_order_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_line_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_line_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
